SistEcomPan/SistEcomPan.Web/Controllers/PagoController.cs
using Entidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Negocio.Implementacion;
using Negocio.Interfaces;
using SistEcomPan.Web.Models.ViewModels;
using SistEcomPan.Web.Tools.Response;

namespace SistEcomPan.Web.Controllers
{
    [Authorize]
    public class PagoController : Controller
    {
        private readonly IPagoService _pagoService;
        private readonly IClienteService _clienteService;
        private readonly IPedidoService _pedidoService;
        private readonly IDetallePagoService _detallePagoService;

        public PagoController(IPagoService pagoService, IClienteService clienteService, IPedidoService pedidoService, IDetallePagoService detallePagoService)
        {
            _pagoService = pagoService;
            _clienteService = clienteService;
            _pedidoService = pedidoService;
            _detallePagoService = detallePagoService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NuevoPago()
        {
            return View();
        }

        [Authorize(Roles = "Cliente")]
        public IActionResult MisPagos()
        {

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            var Pagolista = await _pagoService.Lista();
            List<VMPago> vmPagolista = new List<VMPago>();
            var pedidoCliente = await _pedidoService.Lista();
            var clientes = await _clienteService.Lista();
            foreach (var item in Pagolista)
            {
                var clientePedido = pedidoCliente.Where(x => x.IdPedido == item.IdPedido).First().IdCliente;          
                var nombreCliente = clientes.Where(x => x.IdCliente == clientePedido).First().Nombres + "" +
                                        clientes.Where(x => x.IdCliente == clientePedido).First().Apellidos;

                var codigoPedido = pedidoCliente.Where(x => x.IdPedido == item.IdPedido).First().Codigo;
                var fechaPedido = pedidoCliente.Where(x => x.IdPedido == item.IdPedido).First().FechaPedido;
                vmPagolista.Add(new VMPago
                {
                    IdPago = item.IdPago,
                    IdPedido= item.IdPedido,
                    MontoDePedido = Convert.ToString(item.MontoDePedido),
                    Descuento = Convert.ToString(item.Descuento),
                    MontoTotalDePago =Convert.ToString(item.MontoTotalDePago),
                    MontoDeuda = Convert.ToString(item.MontoDeuda),
                    FechaPago = Convert.ToDateTime(item.FechaDePago),
                    Estado = item.Estado,
                    NombreCliente=nombreCliente,
                    CodigoPedido=codigoPedido,
                    FechaPedido=fechaPedido
                });
            }
            return StatusCode(StatusCodes.Status200OK, new { data = vmPagolista });
        }



        [HttpPost]
        public async Task<IActionResult> Guardar([FromBody] VMPago modelo)
        {
            GenericResponse<VMPago> gResponse = new GenericResponse<VMPago>();

            try
            {
                List<Pagos> listaPagos = new List<Pagos>();         
                if (modelo != null)
                {
                    listaPagos.Add(new Pagos
                    {
                        IdPedido=modelo.IdPedido,
                        MontoDePedido=Convert.ToDecimal(modelo.MontoDePedido),
                        Descuento=Convert.ToDecimal(modelo.Descuento),
                        MontoTotalDePago=Convert.ToDecimal(modelo.MontoTotalDePago),
                        MontoDeuda=Convert.ToDecimal(modelo.MontoDeuda),
                        Estado = modelo.Estado,
                        DetallePago = modelo.DetallePago.Select(detalle => new DetallePago
                        {
                            MontoAPagar = Convert.ToDecimal(detalle.MontoAPagar),
                            PagoDelCliente=Convert.ToDecimal(detalle.PagoDelCliente),
                            DeudaDelCliente= Convert.ToDecimal(detalle.DeudaDelCliente),
                            CambioDelCliente=Convert.ToDecimal(detalle.CambioDelCliente)
                        }).ToList()

                    });
                    
                }

                Pagos pagoCreado = await _pagoService.Registrar(listaPagos.First());

                List<VMPago> vmPagolista = new List<VMPago>();
                
                if (pagoCreado != null)
                {

                    vmPagolista.Add(new VMPago
                    {
                        IdPago=pagoCreado.IdPago,
                        IdPedido = pagoCreado.IdPedido,
                        MontoDePedido = Convert.ToString(pagoCreado.MontoDePedido),
                        Descuento = Convert.ToString(pagoCreado.Descuento),
                        MontoTotalDePago = Convert.ToString(pagoCreado.MontoTotalDePago),
                        MontoDeuda =Convert.ToString(pagoCreado.MontoDeuda),
                        Estado = pagoCreado.Estado,
                        FechaPago=pagoCreado.FechaDePago,
                        DetallePago = pagoCreado.DetallePago.Select(detalle => new VMDetallePago
                        {
                            MontoAPagar = Convert.ToString(detalle.MontoAPagar),
                            PagoDelCliente = Convert.ToString(detalle.PagoDelCliente),
                            DeudaDelCliente = Convert.ToString(detalle.DeudaDelCliente),
                            CambioDelCliente = Convert.ToString(detalle.CambioDelCliente)
                            

                        }).ToList()

                    });
                   
                }

                gResponse.Estado = true;
                gResponse.objeto = vmPagolista.First();

            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensaje = ex.Message;

            }

            return StatusCode(StatusCodes.Status200OK, gResponse);

        }

        [HttpPut]
        public async Task<IActionResult> Editar([FromBody] VMPago modelo)
        {
            GenericResponse<VMPago> gResponse = new GenericResponse<VMPago>();

            try
            {
                List<Pagos> listaPagos = new List<Pagos>();
                if (modelo != null)
                {
                    listaPagos.Add(new Pagos
                    {
                        IdPago=modelo.IdPago,
                        IdPedido = modelo.IdPedido,
                        MontoDeuda = Convert.ToDecimal(modelo.MontoDeuda),
                        Estado = modelo.Estado,
                        DetallePago = modelo.DetallePago.Select(detalle => new DetallePago
                        {
                            MontoAPagar = Convert.ToDecimal(detalle.MontoAPagar),
                            PagoDelCliente = Convert.ToDecimal(detalle.PagoDelCliente),
                            DeudaDelCliente = Convert.ToDecimal(detalle.DeudaDelCliente),
                            CambioDelCliente = Convert.ToDecimal(detalle.CambioDelCliente)
                        }).ToList()

                    });

                }

                Pagos pagoCreado = await _pagoService.Editar(listaPagos.First());

                List<VMPago> vmPagolista = new List<VMPago>();

                if (pagoCreado != null)
                {
                    var pedidoCliente = await _pedidoService.ObtenerNombre();
                    var fechaPedido = pedidoCliente.Where(x => x.IdPedido == modelo.IdPedido).First().FechaPedido;
                    vmPagolista.Add(new VMPago
                    {
                        IdPago = pagoCreado.IdPago,
                        IdPedido = pagoCreado.IdPedido,
                        MontoDeuda = Convert.ToString(pagoCreado.MontoDeuda),
                        Estado = pagoCreado.Estado,
                        NombreCliente=modelo.NombreCliente,
                        MontoTotalDePago=modelo.MontoTotalDePago,
                        MontoDePedido=modelo.MontoDePedido,
                        Descuento=modelo.Descuento,                           
                        FechaPago= Convert.ToDateTime(pagoCreado.FechaDePago),
                        FechaPedido=fechaPedido,
                        DetallePago = pagoCreado.DetallePago.Select(detalle => new VMDetallePago
                        {
                            MontoAPagar = Convert.ToString(detalle.MontoAPagar),
                            PagoDelCliente = Convert.ToString(detalle.PagoDelCliente),
                            DeudaDelCliente = Convert.ToString(detalle.DeudaDelCliente),
                            CambioDelCliente = Convert.ToString(detalle.CambioDelCliente),


                        }).ToList()

                    });

                }

                gResponse.Estado = true;
                gResponse.objeto = vmPagolista.First();

            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensaje = ex.Message;

            }

            return StatusCode(StatusCodes.Status200OK, gResponse);

        }

        [HttpGet]
        public async Task<IActionResult> ObtenerPagoPedido(int searchTerm)
        {
            var Pagolista = await _pagoService.Lista();
            var clientelista = await _clienteService.Lista();
            var PedidosLista = await _pedidoService.Lista();
            var pagosFiltrados = Pagolista.Where(x => x.IdPedido == searchTerm).ToList();
            var MisPagos = pagosFiltrados;

            List<VMPago> vmPagos = new List<VMPago>();

            foreach (var item in MisPagos)
            {
                vmPagos.Add(new VMPago
                {
                    IdPago = item.IdPago,
                    MontoDePedido = Convert.ToString(item.MontoDePedido),

SistEcomPan/SistEcomPan.Web/Controllers/RolController.cs
using Entidades;
using Microsoft.AspNetCore.Mvc;
using Negocio.Interfaces;
using SistEcomPan.Web.Models.ViewModels;
using SistEcomPan.Web.Tools.Response;
using System.Runtime.CompilerServices;

namespace SistEcomPan.Web.Controllers
{
    public class RolController : Controller
    {
        private readonly IRolService _RolService;

        public RolController(IRolService RolService)
        {
            _RolService = RolService;
        }
        public IActionResult Index()
        {

            return View();
        }
        [HttpGet]
        public async Task<IActionResult> ListaRoles()
        {
            var lista = await _RolService.Lista();
            List<VMRol> vmListaRoles = new List<VMRol>();
            foreach (var item in lista)
            {
                vmListaRoles.Add(new VMRol
                {
                    IdRol = item.IdRol,
                    NombreRol=item.NombreRol,
                    Estado = Convert.ToInt32(item.Estado)

                });
            }
            return StatusCode(StatusCodes.Status200OK, vmListaRoles);
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            var Rollista = await _RolService.Lista();
            List<VMRol> vmRollista = new List<VMRol>();
            foreach (var item in Rollista)
            {
                vmRollista.Add(new VMRol
                {
                    IdRol=item.IdRol,
                    NombreRol=item.NombreRol,
                    Estado = Convert.ToInt32(item.Estado)

                });
            }
            return StatusCode(StatusCodes.Status200OK, new { data = vmRollista });
        }

        [HttpPost]
        public async Task<IActionResult> Crear([FromBody] VMRol modelo)
        {
            GenericResponse<VMRol> gResponse = new GenericResponse<VMRol>();

            try
            {
                List<Roles> listaRoles = new List<Roles>();
                List<VMRol> listaVMRoles = new List<VMRol>();
                if (modelo != null)
                {
                    listaVMRoles.Add(modelo);
                    foreach (var item in listaVMRoles)
                    {
                        listaRoles.Add(new Roles
                        {
                            IdRol=item.IdRol,
                            NombreRol=item.NombreRol,
                            Estado=Convert.ToBoolean(item.Estado)
                        });
                    }
                }

                Roles rolCreado = await _RolService.Crear(listaRoles.First());

                List<VMRol> vmRoleslista = new List<VMRol>();
                List<Roles> listRoles = new List<Roles>();
                if (rolCreado != null)
                {
                    listRoles.Add(rolCreado);


                    foreach (var item in listRoles)
                    {
                        vmRoleslista.Add(new VMRol
                        {
                            IdRol=item.IdRol,
                            NombreRol=item.NombreRol,
                            Estado = Convert.ToInt32(item.Estado)
                        });
                    }
                }

                gResponse.Estado = true;
                gResponse.objeto = vmRoleslista.First();

            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensaje = ex.Message;

            }

            return StatusCode(StatusCodes.Status200OK, gResponse);

        }

        [HttpPut]
        public async Task<IActionResult> Editar([FromBody] VMRol modelo)
        {
            GenericResponse<VMRol> gResponse = new GenericResponse<VMRol>();

            try
            {

                List<Roles> listaRoles = new List<Roles>();
                List<VMRol> listaVMRoles = new List<VMRol>();
                if (modelo != null)
                {
                    listaVMRoles.Add(modelo);
                    foreach (var item in listaVMRoles)
                    {
                        listaRoles.Add(new Roles
                        {
                            IdRol = item.IdRol,
                            NombreRol = item.NombreRol,
                            Estado = Convert.ToBoolean(item.Estado)
                        });
                    }
                }

                Roles RolEditado = await _RolService.Editar(listaRoles.First());

                List<Roles> listRoles = new List<Roles>();
                List<VMRol> vmRolesLista = new List<VMRol>();
                if (RolEditado != null)
                {
                    listRoles.Add(RolEditado);
                    foreach (var item in listRoles)
                    {
                        vmRolesLista.Add(new VMRol
                        {
                            IdRol=item.IdRol,
                            NombreRol=item.NombreRol,
                            Estado = Convert.ToInt32(item.Estado)
                        });
                    }
                }

                gResponse.Estado = true;
                gResponse.objeto = vmRolesLista.First();

            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensaje = ex.Message;

            }

            return StatusCode(StatusCodes.Status200OK, gResponse);

        }

        [HttpDelete]
        public async Task<IActionResult> Eliminar(int IdRol)
        {
            GenericResponse<string> gResponse = new GenericResponse<string>();

            try
            {
                gResponse.Estado = await _RolService.Eliminar(IdRol);

            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensaje = ex.Message;

            }

            return StatusCode(StatusCodes.Status200OK, gResponse);

        }

    }
}

SistEcomPan/SistEcomPan.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mi Tienda - @ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    @await RenderSectionAsync("Estilos", required: false)
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-desktop"></i>
                </div>
                <div class="sidebar-brand-text mx-3">MI TIENDA</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            @if (User.IsInRole("Cliente"))
            {
                <!-- Nav Item - Dashboard -->
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("DashBoardCliente","DashBoard")">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Panel de Control</span>
                    </a>
                </li>
            }
            @if (!User.IsInRole("Cliente"))
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","DashBoard")">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Panel de Control</span>
                    </a>
                </li>
                <!-- Nav Item - Administración Collapse Menu -->
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministracion">
                        <i class="fas fa-fw fa-cog"></i>
                        <span>Administración</span>
                    </a>
                    <div id="collapseAdministracion" class="collapse" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" href="@Url.Action("Index","Usuario")">Usuarios</a>
                            <a class="collapse-item" href="@Url.Action("Index","Rol")">Roles</a>
                            <a class="collapse-item" href="@Url.Action("Index","Cliente")">Clientes</a>
                        </div>
                    </div>
                </li>

            }
            @if (!User.IsInRole("Cliente"))
            {
                <!-- Nav Item - Inventario Collapse Menu -->
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInventario">
                        <i class="fas fa-fw fa-clipboard-list"></i>
                        <span>Inventario</span>
                    </a>
                    <div id="collapseInventario" class="collapse" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" href="@Url.Action("Index","Categoria")">Categorias</a>
                            <a class="collapse-item" href="@Url.Action("Index","Producto")">Productos</a>
                            <a class="collapse-item" href="@Url.Action("Index","Distrito")">Distritos</a>
                        </div>
                    </div>
                </li>
            }
            @if (User.IsInRole("Administrador") || User.IsInRole("Cliente"))
            {
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePago">
                        <i class="fas fa-fw fa-tags"></i>
                        <span>Pagos</span>
                    </a>
                    <div id="collapsePago" class="collapse" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            @if (User.IsInRole("Administrador"))
                            {
                                <a class="collapse-item" href="@Url.Action("NuevoPago","Pago")">Nuevo Pago</a>
                            }
                            @if (User.IsInRole("Cliente"))
                            {
                                <a class="collapse-item" href="@Url.Action("MisPagos","Pago")">Mis Pagos</a>
                            }

                        </div>
                    </div>
                </li>
            }

            <!-- Nav Item - Venta Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePedido">
                    <i class="fas fa-fw fa-tags"></i>
                    <span>Pedidos</span>
                </a>
                <div id="collapsePedido" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        @if (!User.IsInRole("Cliente"))
                        {
                            <a class="collapse-item" href="@Url.Action("NuevoPedido","Pedido")">Nuevo Pedido</a>
                            <a class="collapse-item" href="@Url.Action("Index","Pedido")">Pedidos</a> 
                            <a class="collapse-item" href="@Url.Action("HistorialPedido","Pedido")">Historial Pedido</a>
                            <a class="collapse-item" href="@Url.Action("Index","Devolucion")">Devoluciones</a>
                        }
                        @if (User.IsInRole("Cliente")) {
                            <a class="collapse-item" href="@Url.Action("NuevoPedido","Pedido")">Nuevo Pedido</a>
                            <a class="collapse-item" href="@Url.Action("MisPedidos","Pedido")">Mis Pedidos</a>
                        }

                    </div>
                </div>
            </li>
            @if (User.IsInRole("Administrador") || User.IsInRole("Cliente"))
            {
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMensaje">
                        <i class="fas fa-fw fa-tags"></i>
                        <span>Mensajes</span>
                    </a>
                    <div id="collapseMensaje" class="collapse" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            @if (User.IsInRole("Administrador"))
                            {
                                <a class="collapse-item" href="@Url.Action("Index","Mensaje")">Nuevo Mensaje</a>
                            }
                            @if (User.IsInRole("Cliente"))
                            {
                                <a class="collapse-item" href="@Url.Action("MisMensajes","Mensaje")">Mis Mensajes</a>
                            }
                        </div>
                </div>
            </li>
            }
            <!-- Nav Item - Reportes Collapse Menu -->
@*            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReportes">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Reportes</span>
                </a>
                <div id="collapseReportes" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Reporte")">Reporte de Pedidos</a>
                    </div>
                </div>
            </li> *@

            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!--Sidebar Toggle (Topbar)--> 
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
@*                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="perfil.html">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Salir
                                </a>
                            </div>
                        </li> *@
                        @await Component.InvokeAsync("MenuUsuario")
                       
                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>